name: Skill CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  
jobs:
  check-branch:
    name: Checkout Skill Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Verify branch exists in remote
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          git ls-remote --heads origin
          echo "✅ Repository state validated"

  build:
    name: Build Skill
    uses: matterway/tools-mw-auto-updater/.github/workflows/build.yml@main
    needs: check-branch
    secrets: inherit
    if: always() && !cancelled()

  lint:
    name: Lint Code
    uses: matterway/tools-mw-auto-updater/.github/workflows/lint.yml@main
    needs: check-branch
    secrets: inherit
    if: always() && !cancelled()

  dependency-check:
    name: Check Unused Dependencies
    uses: matterway/tools-mw-auto-updater/.github/workflows/dependency-check.yml@main
    needs: check-branch
    secrets: inherit
    if: always() && !cancelled()

  licenses-check:
    name: Check Licenses
    uses: matterway/tools-mw-auto-updater/.github/workflows/licenses-check.yml@main
    needs: check-branch
    secrets: inherit
    if: always() && !cancelled()
